### ISSUE TITLE
Bug: The InputMap action "pressed_action" doesn't exist. 

### ISSUE THREAD

**Issue by izzint** [TechMan06/Openscop#7]
an error like `The InputMap action "pressed_action" doesn't exist.` is spammed in the editor and in play mode, does anyone know what causes this? i cant rlly talk over discord rn cause im at school :p 

any help is really appreciated !!

(p.s, heres my system info)
`Godot v4.1.3.stable - macOS 13.6.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)`

**Comment by TechMan06** [comment]
Fixed on commit https://github.com/TechMan06/Openscop/commit/4a3921994987a1f2372cf3f4dde4798fc2fa71e2
